name: Changesets

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  changesets:
    name: Changesets
    runs-on: ubuntu-latest

    environment: release

    if: github.repository == 'jakebailey/dprint-plugin-gofumpt'

    permissions:
      contents: write
      checks: read
      issues: read
      pull-requests: write
      id-token: write

    steps:
      - name: Obtain GitHub App token
        id: octo-sts
        uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        with:
          scope: jakebailey/dprint-plugin-gofumpt
          identity: changesets

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          filter: blob:none
          token: ${{ steps.octo-sts.outputs.token }}

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          package-manager-cache: false

      # Ensure a recent npm for OIDC trusted publishing to npmjs.com.
      - run: npm install -g npm@latest

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: true
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable

      - name: Capture new release version
        id: version
        run: |
          pnpm changeset version
          echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
          git restore .

      - id: changesets
        uses: changesets/action@22ccf9aa43179fe9e27dc62e575971d28cce197c # v2.0.0
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          title: 'Release v${{ steps.version.outputs.version }}'
          commit: 'Release v${{ steps.version.outputs.version }}'
          version: pnpm run version
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}

      - name: Upload release assets
        if: steps.changesets.outputs.published == 'true'
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          files: |
            plugin.wasm
            metadata/schema.json
