name: Release

# We trigger on pushes to tags, since they are pushed with a deploy key
# in the changesets workflow in order to bypass GHA token restrictions.
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions: read-all

# https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/nodejs#generating-provenance

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.repository == 'jakebailey/dprint-plugin-gofumpt'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '24'
          package-manager-cache: false
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: true
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: stable

      - run: pnpm hereby build

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: artifact
          path: |
            plugin.wasm
            metadata/schema.json

  publish:
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: artifact
      - name: Wait for release to exist
        env:
          GH_TOKEN: ${{ github.token }}
          GH_PAGER: ''
        run: |
          until gh release view "${{ github.ref_name }}" --repo "${{ github.repository }}"; do
            echo "Waiting for release ${{ github.ref_name }} to be created..."
            sleep 5
          done
      - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: |
            plugin.wasm
            metadata/schema.json
